backend:
  squash_merges: true
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "public/assets/" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/" # The src attribute for uploaded media will begin with /images/uploads
locale: "de" # Deutsche Oberfläche

collections:
  - name: "start" # Used in routes, e.g., /admin/collections/blog
    label: "Startseite" # Used in the UI
    folder: "src/content/start" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Reihenfolge", name: "order", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "veranstaltungen" # Used in routes, e.g., /admin/collections/veranstaltungen
    label: "Veranstaltungen" # Used in the UI
    folder: "src/content/veranstaltungen" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Erstellungsdatum", name: "pubDate", widget: "datetime" }
      - { label: "Veranstaltungsdatum und Start-Uhrzeit",  name: "eventDate", widget: "datetime"}
      - { label: "Veranstaltungsort", name: "location", widget: "string", required: false }
      - { label: "Titelbild", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: mitglieder
    label: Mitglieder
    folder: src/content/mitglieder/
    media_folder: ""
    public_folder: ""
    create: true
    slug: "{{name}}"
    fields:
      - {
          label: "Name",
          name: "name",
          widget: "string",
          hint: "Vor- und Nachname",
        }
      - {
          label: Rolle,
          name: position,
          widget: "select",
          options:
            [
              "1. Vorsitzender",
              "2. Vorsitzender",
              "Kassenwart",
              "Gartenbau",
              "Sportheimwart",
              "Schriftführer",
            ],
          required: false,
        }
      - { label: Stammtisch, name: stammtisch, widget: boolean, default: false }
      - { label: Dart, name: dart, widget: boolean, default: false }
      - {
          label: Email,
          name: email,
          widget: string,
          hint: "Wird nicht öffentlich angezeigt",
          required: false,
        }
      - { label: Image, name: authorimage, widget: image, required: false }
